## Project information
site_name: 30daymapchallengelatam
site_url: https://github.com/ambarja/30DayMapChallengeLatam
site_description: 🗺️ Mapatón orientada a compartir mapas temáticos por cada día del mes de setiembre del presente año📅 empleando software libre de código abierto con datos abiertos 🌎🐧.
site_author: https://ambarja.github.io/

## Repository
repo_name: 30DayMapChallengeLatam
repo_url: https://github.com/ambarja/30DayMapChallengeLatam
edit_uri: edit/main/docs/ 

# Copyright
copyright: <a href="https://twitter.com/antony_barja" title="@antony_barja" target="_blank">Creado por <b>Antony Barja| @antony_barja</b></a> | <a href="https://creativecommons.org/licenses/by-sa/4.0/!" title="Se non specificato diversamente, tutti i contenuti sono soggetti alla licenza Creative Commons Attribution-ShareAlike 4.0 licence (CC BY-SA)" target="_blank" class="link-dark text-decoration-none">Licenza CC-BY-SA-4.0</a>

## Social Media
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/solid/house
      link: ./
      name: Home Page
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/antony_barja
      name: account twitter  
    - icon: fontawesome/brands/github
      link: https://github.com/ambarja/30DayMapChallengeLatam
      name: Repository GitHub
    - icon: fontawesome/brands/paypal
      link: https://www.paypal.com/paypalme/ambarja
      name: Donación a 30daymapchallengelatam con PayPal

  #analytics:
    #provider: google
    #property: UA-122084242-1

## Configuration
theme:
  name: material
  custom_dir: docs/theme_override/
  static_templates:
    - 404.html
  palette:
    scheme: preference
  language: es
  features:
    - navigation.top
#   - navigation.instant
    - navigation.tabs
 #  - header.autohide
    - search.suggest
  # - search.highlight
    - search.share
  palette:
    primary: amber
    accent: amber
  font:
    text: Open Sans
    code: Cutive Mono
  favicon: img/favicon.ico
  icon:
  logo: img/30DMC_Tag_.svg

plugins:
- tags:
    tags_file: tags.md
- search
# - mkdocstrings
# - autolinks
# - macros 

- rss:
    abstract_chars_count: 160
    date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%d-%m-%Y"
      # datetime_format: "%Y-%m-%d"
    image: https://materialmkdocs-gb.readthedocs.io/it/latest/img/hfc_rss.png
    feed_ttl: 1440
    length: 20
    pretty_print: false
    #  match_path: ".*"
    #  url_parameters:
    #      utm_source: "documentation"
    #      utm_medium: "RSS"
    #      utm_campaign: "feed-syndication"

markdown_extensions:
- footnotes
- toc:
    permalink: ↵
- meta
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

## Custom theme additions
extra_javascript:
   - stylesheets/extra.js

extra_css:
   - stylesheets/gbextra.css

## Page tree
nav:
    - Inicio: index.md
    - Consideraciones: 
        - Presentación: presentacion.md
        - Licencia: LICENSE_my.md

    - 2022 Challenge:
        - día 01: dia01.md
    - Estadística: estadistica2022.md
    - Acerca de mi:
        - Presentación: aboutme.md
        - Soporte: supporter.md
    # - Webmaster: webmaster/gbvitrano.md
  # - Tags: tags.md
