## Project information
site_name: 30daymapchallengelatam
site_url: https://ambarja.github.io/30daymapchallengelatam/
site_description: 🗺️ Mapatón orientada a compartir mapas temáticos por cada día del mes de setiembre del presente año📅 empleando software libre de código abierto con datos abiertos 🌎🐧.
site_author: https://ambarja.github.io/

## Repository
repo_name: 
repo_url: https://github.com/opendatasicilia/HfcQGIS-md
edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: <a href="https://twitter.com/antony_barja" title="@antony_barja" target="_blank">Creado por <b>Antony Barja| @antony_barja</b></a> | <a href="https://creativecommons.org/licenses/by-sa/4.0/!" title="Se non specificato diversamente, tutti i contenuti sono soggetti alla licenza Creative Commons Attribution-ShareAlike 4.0 licence (CC BY-SA)" target="_blank" class="link-dark text-decoration-none">Licenza CC-BY-SA-4.0</a>

## Social Media
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: fontawesome/solid/house
      link: https://hfcqgis.opendatasicilia.it/
      name: Home Page
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/opendatasicilia
      name: account twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/opendatasicilia/
      name: gruppo facebook OpenDataSicilia
    - icon: fontawesome/brands/github
      link: https://github.com/opendatasicilia/HfcQGIS-md
      name: Repository GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/opendatasicilia
      name: gruppo Telegram OpenDataSicilia
    - icon: fontawesome/solid/envelope
      link: https://groups.google.com/forum/#!forum/opendatasicilia
      name: mailing list OpenDataSicilia
    - icon: fontawesome/brands/paypal
      link: https://www.paypal.com/paypalme/pigrecoinfinito
      name: Donazione a HfcQGIS con PayPal
    - icon: fontawesome/solid/rss
      link: https://hfcqgis.opendatasicilia.it/feed_rss_created.xml
      name: Feed RSS

  #analytics:
    #provider: google
    #property: UA-122084242-1

## Configuration
theme:
  name: material
  custom_dir: docs/theme_override/
  static_templates:
    - 404.html
  palette:
    scheme: preference
  language: es
  features:
    - navigation.top
#   - navigation.instant
    - navigation.tabs
 #  - header.autohide
    - search.suggest
  # - search.highlight
    - search.share
  palette:
    primary: amber
    accent: deep black
  font:
    text: Open Sans
    code: Cutive Mono
  favicon: img/favicon.ico
  icon:
  logo: img/30DMC_Tag_.svg

plugins:
- tags:
    tags_file: tags.md
- search
# - mkdocstrings
# - autolinks
# - macros 

- rss:
    abstract_chars_count: 160
    date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%d-%m-%Y"
      # datetime_format: "%Y-%m-%d"
    image: https://materialmkdocs-gb.readthedocs.io/it/latest/img/hfc_rss.png
    feed_ttl: 1440
    length: 20
    pretty_print: false
    #  match_path: ".*"
    #  url_parameters:
    #      utm_source: "documentation"
    #      utm_medium: "RSS"
    #      utm_campaign: "feed-syndication"

markdown_extensions:
- footnotes
- toc:
    permalink: ↵
- meta
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

## Custom theme additions
extra_javascript:
   - stylesheets/extra.js

extra_css:
   - stylesheets/gbextra.css

## Page tree
nav:
    - Home: index.md

    - About:
        - OpenDataSicilia: ods.md
        - Autore HfcQGIS: autore.md
        - Webmaster: webmaster/gbvitrano.md
        - Traduzione: traduzione.md
        - Release: release.md
        - Changelog: changelog.md
        - Pull Request: pull-request.md
        - gis-stackexchange: gis-stackexchange.md
        - Sitografia: sitografia_field_calc.md
        - Risorse: risorse.md
        - Disclaimer: disclaimer.md
        - Licenza: LICENSE_my.md
      #  - Informativa privacy estesa: privacy.md
    # - Webmaster: webmaster/gbvitrano.md
  # - Tags: tags.md
